### ISSUE TITLE
Failing to find custom color palettes?

### ISSUE THREAD

**Issue by hneth** [hneth/unikn#4]
When using `seecol(pal = list(pal_1, pal_2))` to compare (or scale) multiple color palettes, some custom color palettes (e.g., `pal_freiburg_basic` from the README) are currently not found.

**Comment by nigradwohl** [comment]
This was due to an error with the isHexCol() function, which did not recognize hexadecimal colors starting with lowercase letters. 
I changed the function accordingly.

**Comment by hneth** [comment]
Excellent & thanks a lot for the fix!
