### ISSUE TITLE
Specify palette name when comparing customized palettes with `seecol` function

### ISSUE THREAD

**Issue by dpzhang** [hneth/unikn#5]
When comparing different custom palettes using `seecol` function, is there any way to specify palette names instead of the default "pal#"? Thanks!

**Comment by hneth** [comment]
This functionality currently does not exist, but would make perfect sense.   

As the palettes can be specified in a variety of ways, there is no simple solution that handles all cases.  But we'll see what we can do to improve on the current version.

**Thanks** for your suggestion — and please stay tuned for an update soon, 
Hans

**Comment by hneth** [comment]
The `seecol()` function now allows for a `pal_names` argument.  Providing a character vector of names allows re-labeling (all or only the custom) color palettes shown in the comparison plot.  

Perhaps you could check out this feature — in the current development version of the **unikn** package — and let us know whether this meets your needs? 

Best,
Hans

**Comment by dpzhang** [comment]
Thank you so much for the quick patch. Just tested out and it works perfectly! The package will be super helpful to my project, and thanks again for all your amazing work!
