### ISSUE TITLE
dim parameter not working

### ISSUE THREAD

**Issue by leonardosnr** [hneth/unikn#7]
Dear,

When I try to use the dim parameter in the slide command (slide(dim = c(3, 1)), it does not work and it shows a square. Any thoughts about what is going on?

Best

**Comment by hneth** [comment]
Hi Leonardo,

thanks for your note.  You're right:  The `slide()` function did not propagate the `dim` argument properly.  The updated development version (v0.4.0.9003) fixes this bug, but it's hard to see the difference within R or RStudio (as plots are automatically scaled to the size of the canvas/plotting device).

Best,
Hans

**Comment by hneth** [comment]
Issue has been fixed in v0.4.0.9004 of **unikn**.
