### ISSUE TITLE
centering text

### ISSUE THREAD

**Issue by leonardosnr** [hneth/unikn#8]
Any tip on how to center the text? It seems it depends on the length and size of the text, but I could not figure out how to do it.

**Comment by hneth** [comment]
There's currently no support for centering lines of text.  This would require an `x_layout` argument (similar to `y_layout`), but as our focus was on left-adjusted labels, there's currently no easy way to automatically center text.  

For individual instances, fiddling with `y`-values gets the job done.  But I see that this is awkward when creating multiple plots.  Is this a functionality you urgently need for some project?

**Comment by hneth** [comment]
The latest development version (**unikn** v0.4.0.9004) provides a `x_layout` argument to the `mark()`, `slide()`, `uline()` and `heading()` functions, with options for "center", "left", or "right"-adjusting text labels.

Please test and let me know whether this works for you.

**Comment by hneth** [comment]
Issue has been fixed in version 0.4.0.9004 of **unikn**.
 
See documentation and https://hneth.github.io/unikn/dev/articles/text.html for details.
